# Built with Jekyll 3.2.0

# Setup
title:               'Fibra Project'
tagline:             'A graphical expression of interpretation.'
description:         'Personal modeling tool for node rich data.'
url:                 'fibra'
#baseurl:             'http://hdlab.stanford.edu/fibra'
urlimg: 	'http://hdlab.stanford.edu/fibra/assets/'
keywords:    "digital humanities, linked data, Stanford University, Humanities+Design"
source_link: "https://github.com/humanitiesplusdesign/fibra/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-89834843-1

gems:
  - jekyll-redirect-from

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections
collections:
  studies:
    output: true
  meetings:
    output: true
  designs:
    output: true
  splash:
    output: false

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Exclusions from the final site
exclude: [optional, vendor]


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#fff'
  blue:      'rgb(58,171,210)'
  sanfrancisco:  '#8f8f8f'
  portland:      '#292929'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#FF8F19'
  turquoise: '#0fbfcf'
  red:       'rgb(198, 58,70)'
  blueprint:   '#489df9'



