# Built with Jekyll 3.2.0

# Setup
title:               Fibra Project
tagline:             'A graphical expression of interpretation.'
description:         ''
url:                 'fibra'
baseurl:             'http://hdlab.stanford.edu/fibra'

gems:
  - jekyll-redirect-from

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections
collections:
  studies:
    output: true
  meetings:
    output: true
  designs:
    output: false

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.5

# Exclusions from the final site
exclude: [optional, vendor]


